name: Initialize Template

# Only runs once when repository is created from template
on:
  push:
    branches: [main]

jobs:
  initialize:
    if: github.repository != 'cto4ai/ai-first-docs'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - uses: actions/checkout@v4

      - name: Personalize repository
        run: |
          # Extract repository information
          REPO_NAME="${{ github.event.repository.name }}"
          GITHUB_ORG="${{ github.repository_owner }}"
          COMPANY_NAME="${{ github.repository_owner }}"
          DOCROOT="docs"
          ECOSYSTEM="claude"

          echo "🚀 Personalizing repository for: $COMPANY_NAME / $REPO_NAME"

          # Replace variables in all markdown and JSON files
          echo "📝 Replacing template variables..."
          find . -type f \( -name "*.md" -o -name "*.json" -o -name "*.template" \) \
            ! -path "./.git/*" | while read file; do
            sed -i.bak \
              -e "s/{{REPO_NAME}}/$REPO_NAME/g" \
              -e "s/{{GITHUB_ORG}}/$GITHUB_ORG/g" \
              -e "s/{{COMPANY_NAME}}/$COMPANY_NAME/g" \
              -e "s/{{DOCROOT}}/$DOCROOT/g" \
              -e "s/{{ECOSYSTEM}}/$ECOSYSTEM/g" \
              "$file"
          done

          # Clean up backup files
          find . -name "*.bak" -delete
          echo "✅ Template variables replaced"

          # Create .mcp-config.json from template
          if [ -f ".mcp-config.json.template" ]; then
            mv .mcp-config.json.template .mcp-config.json
            echo "✅ .mcp-config.json created"
          fi

          # Process docs/skills/README.md.template
          if [ -f "docs/skills/README.md.template" ]; then
            mv docs/skills/README.md.template docs/skills/README.md
            echo "✅ docs/skills/README.md created"
          fi

          # Process any other .template files
          find . -name "*.template" -type f ! -path "./.git/*" | while read template; do
            target="${template%.template}"
            mv "$template" "$target"
            echo "✅ Created ${target}"
          done

          # Clean up template-only files from .github/DOCUMENTATION/
          echo "🧹 Removing template development files..."
          rm -f .github/DOCUMENTATION/V2.0-RESTRUCTURE-PLAN.md
          rm -f .github/DOCUMENTATION/TEMPLATE-README.md
          rm -rf .github/DOCUMENTATION/future-features
          echo "✅ Template-only files removed"

          # Swap README files
          echo "📄 Swapping README files..."
          rm README.md
          mv USER_README.md README.md
          echo "✅ README.md swapped"

      - name: Create setup issue
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚀 AI-First Documentation Repository Initialized',
              body: `## Welcome to your AI-first documentation repository!

              Your repository has been automatically configured.

              ### ✅ What's Ready
              - Documentation structure in \`docs/\`
              - MCP configuration with docroot = \`docs/\`
              - Simple document templates
              - Claude Ecosystem integration ready

              ### 📋 Next Steps

              **1. Install Prerequisites** (choose one or both):
              - [ ] Install [github-repos-manager-mcp](https://github.com/cto4ai/github-repos-manager-mcp) v3.0+ (for Claude Desktop)
              - [ ] Install [github-docs-skill](https://github.com/cto4ai/claude-skills) (for Claude.ai)

              **2. Test Integration**
              \`\`\`
              You: "Get the catalog of documents in this repository"
              Claude: [Shows docs/ structure]
              \`\`\`

              **3. Start Documenting**
              - Use templates in \`docs/templates/\`
              - Work through AI (Claude Desktop with MCP or Claude.ai with Skills)
              - Or edit directly in GitHub

              ### 📖 Resources
              - [AI-First Strategy](.github/DOCUMENTATION/ai-first-strategy.md) - Explains the approach
              - [Document Templates](docs/templates/) - Policy, procedure, and guide templates
              - [MCP Configuration](.mcp-config.json) - Repository settings

              ### 🎯 Quick Examples

              **Create a policy:**
              \`\`\`
              You: "Create a remote work policy using the policy template"
              \`\`\`

              **Find documents:**
              \`\`\`
              You: "Show me all the policies in this repository"
              \`\`\`

              **Update content:**
              \`\`\`
              You: "Update the [document name] to include [new requirement]"
              \`\`\`

              Close this issue when setup is complete!`
            })

      - name: Commit personalized changes
        run: |
          # Delete this initialization workflow
          rm .github/workflows/init-template.yml

          # If .github/workflows/ is now empty, remove it
          if [ -z "$(ls -A .github/workflows 2>/dev/null)" ]; then
            rm -rf .github/workflows
            echo "✅ Empty workflows directory removed"
          fi

          # Configure git
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # Check if there are changes to commit
          if [[ -n $(git status --porcelain) ]]; then
            echo "📦 Committing personalized changes..."
            git add -A
            git commit -m "Initialize from ai-first-docs template

            - Replace template variables
            - Create .mcp-config.json from template
            - Swap template README with repo README
            - Remove template development files
            - Remove initialization workflow

            Repository: ${{ github.repository }}
            Owner: ${{ github.repository_owner }}"

            echo "⬆️ Pushing changes..."
            git push
            echo "✅ Repository initialization complete!"
          else
            echo "ℹ️ No changes to commit"
          fi
